name: hitnewsapp
version: 2
libraries:
- name: webpy
  version: "0.36"
- name: lxml
  version: "2.3.4"
  
cron:
- description: timing_task
  url: /crawler
  schedule: "*/3 * * * *"
cron:
- description: timing_task
  url: /push
  schedule: "*/30 * * * *"